name: she_bloom
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1

#
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/flower.svg
    - assets/images/dailyfood.jpg
    - assets/images/picks.jpg
    - assets/images/menstruation.jpg
    - assets/images/bloodflow.jpg
    - assets/images/checkup.png
    - assets/images/cramps.png
    - assets/images/depression.png
    - assets/images/pcos.png
    - assets/images/pills.jpg
    - assets/images/safty.png
    - assets/images/breastCancer.jpg
    - assets/images/trackClock.png
    - assets/images/vaccination.png
    - assets/images/eggs.jpg


  fonts:
     - family: YesevaOne
       fonts:
         - asset: assets/fonts/YesevaOne.ttf
     - family: Gaqire
       fonts:
         - asset: assets/fonts/Gaqire.otf

