name: she_bloom
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  # Firebase Packages
  firebase_core: ^3.6.2
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4



  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

#
flutter:

  uses-material-design: true

  assets:
    - assets/images/flower.svg
    - assets/images/dailyfood.jpg
    - assets/images/picks.jpg
    - assets/images/menstruation.jpg
    - assets/images/bloodflow.jpg
    - assets/images/checkup.png
    - assets/images/cramps.png
    - assets/images/depression.png
    - assets/images/pcos.png
    - assets/images/pills.jpg
    - assets/images/safty.png
    - assets/images/breastCancer.jpg
    - assets/images/trackClock.png
    - assets/images/vaccination.png
    - assets/images/eggs.jpg


  fonts:
     - family: YesevaOne
       fonts:
         - asset: assets/fonts/YesevaOne.ttf
     - family: Gaqire
       fonts:
         - asset: assets/fonts/Gaqire.otf

